name: tagpr

on:
  push:
    branches:
      - main

jobs:
  tagpr:
    name: tagpr
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: Songmu/tagpr@v1
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/release
        if: steps.tagpr.outputs.tag != ''
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
