name: tagpr

on:
  push:
    branches:
      - main

jobs:
  tagpr:
    name: tagpr
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PR_MAKER_APP_ID }}
          private-key: ${{ secrets.PR_MAKER_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - uses: Songmu/tagpr@v1
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      - uses: ./.github/actions/release
        if: steps.tagpr.outputs.tag != ''
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
